### ISSUE TITLE
Если в названи есть &, то поиск обрезает по нему. Поиск из карточки и из кабинета.

### ISSUE THREAD

**Issue by aldrd** [Mymem/site_ru#103]
https://mymem.me/mneme/c/cinema/movies;v/catalog/genres/aFAA3aH9SISO1pm0YL8U4A/AAAAAAAAAAAAAAAAAAAHzg;f/NCmlcMuBTZ6f8P9R4zF5KA;d/IwUCBK-XQzSjOdE4VhMrxA

**Comment by shabanovd** [comment]
в тот момент не было индекса просто, сейчас все ищет

**Comment by aldrd** [comment]
Я про поиск а гугле
