### ISSUE TITLE
В киоске после раздела "самые популярные" стоит сделать раздел "черновые релизы"

### ISSUE THREAD

**Issue by aldrd** [Mymem/site_ru#107]
Показывать там все фильмы с черновыми релизами (но без финальных). Показывать все независимо от значимости. Показывать за последний год.
Там будут как черновые релизы фильмов из кино (звук line), так и все любительские и полу-профессиональные переводы.
Возможно, что этот раздел имеет  смысл показывать только для России.

**Comment by shabanovd** [comment]
done
