### ISSUE TITLE
закрытие большой карточки иногда ведет на черный экран. Нажатие на экран открывает фильм под которым проступает фон.

### ISSUE THREAD

**Issue by aldrd** [Mymem/site_ru#112]

**Comment by aldrd** [comment]
<img width="1318" alt="default" src="https://cloud.githubusercontent.com/assets/2474607/10204045/347ad2fe-67c2-11e5-8ebd-86ec74354988.PNG">
Черный экран. При нажатии на консоль картинка проявилась.

**Comment by shabanovd** [comment]
fixed
