### ISSUE TITLE
Картинка в карточке не того языка

### ISSUE THREAD

**Issue by aldrd** [Mymem/site_ru#118]
https://mymem.me/mneme/c/cinema/movies;v/library/6iKoOV1tQAalI-HoD0wSQg;f/genres;d/tUIQYXwxRx-hZjumwa8eOQ

https://mymem.me/cabinet/#tUIQYXwxRx-hZjumwa8eOQ
<img width="1071" alt="default" src="https://cloud.githubusercontent.com/assets/2474607/10268336/e27851f8-6abd-11e5-9f7d-2db57bd851e1.PNG">

**Comment by shabanovd** [comment]
fixed
