### ISSUE TITLE
Фильм 2017 года стоит в конце списка

### ISSUE THREAD

**Issue by aldrd** [Mymem/site_ru#122]
https://mymem.me/mneme/c/cinema/movies;v/catalog/haeeb709TV-7RGLxtdOpbA/Sj38QGiGT5q-C0Rg2y0bzw/Cz9oh1kMQAimmr7kPeK7RQ;f/NCmlcMuBTZ6f8P9R4zF5KA;d/FdMErFlqRt6SXAhAiQD1zw

**Comment by shabanovd** [comment]
в каталоге формируется по популярности, а не по хронологии
