### ISSUE TITLE
Ссылка на imdb есть, но зачек не подсвечен

### ISSUE THREAD

**Issue by aldrd** [Mymem/site_ru#126]
https://mymem.me/mneme/c/cinema/movies;v/catalog/TluxwFsoTJ-4qHTm3K2yBA/AAAAAAAAAAAAAAAAAAAHxg;f/NCmlcMuBTZ6f8P9R4zF5KA;d/iYTe26l7QpiRPHevwADAJA

https://mymem.me/mneme/c/cinema/movies;v/catalog/TluxwFsoTJ-4qHTm3K2yBA/AAAAAAAAAAAAAAAAAAAHxg;f/NCmlcMuBTZ6f8P9R4zF5KA;d/JEXIviuZRHe34oKukHjE5g - есть обе ссылки

**Comment by shabanovd** [comment]
fixed
