### ISSUE TITLE
У некоторых стран нет картинок, хотя топовые фильмы есть и они с картинками

### ISSUE THREAD

**Issue by aldrd** [Mymem/site_ru#128]
<img width="1063" alt="default" src="https://cloud.githubusercontent.com/assets/2474607/10419105/762c8420-7075-11e5-84cc-e8e73266044d.PNG">

**Comment by shabanovd** [comment]
отсутствие картинок подправил, а вот с "человеческим ликом" которые нуно подправить страну у фильмов
