### ISSUE TITLE
Фильм есть в киоске (в релизах), но поиск этого не показывает

### ISSUE THREAD

**Issue by aldrd** [Mymem/site_ru#130]
<img width="722" alt="default" src="https://cloud.githubusercontent.com/assets/2474607/10440848/6246cd22-714b-11e5-95e7-c3be068581bd.PNG">

**Comment by shabanovd** [comment]
она не на первом экране, если прокрутить "релизы" до второго экрана (будет подгрузка) и он покажется как в киоске
