### ISSUE TITLE
В Chrome на OS X не работает регистрация 

### ISSUE THREAD

**Issue by MihaxXx** [Mymem/site_ru#132]
http://net2ftp.ru/node0/mikes22@yandex.ru/Screenshot_on_13,10_at_21-00-04.png

**Comment by shabanovd** [comment]
@MihaxXx проверил у себя на хроме, все ок.

**Comment by MihaxXx** [comment]
Нашёл откуда ноги растут - uBlock
Обычно таких финтов нет.

**Comment by gev** [comment]
а вот эти картинки открываются?
https://mymem.me/icons/networks/webicon-facebook.svg
https://mymem.me/icons/networks/webicon-googleplus.svg

PS у меня тоже ок

**Comment by gev** [comment]
и что он заблокировал?

**Comment by MihaxXx** [comment]
Картиночки открываются
Что заблокировал не кайф смотреть, просто отключил его на этом сайте, даже если будет реклама, то можно позволить в данной ситуации

**Comment by MihaxXx** [comment]
После логина не отображается какая-то иконка в правом верхнем углу - типо изображение не загрузилось

**Comment by gev** [comment]
это аватар, уже исправлено

**Comment by MihaxXx** [comment]
исправлено это уже внесли правки, но ещё не выкатили на сайт?

**Comment by shabanovd** [comment]
да
