### ISSUE TITLE
Добавить возможность горизонтального скролинга перемещением мышки с удержанием левой кнопки 

### ISSUE THREAD

**Issue by MihaxXx** [Mymem/site_ru#133]

**Comment by shabanovd** [comment]
@MihaxXx есть возможность горизонтального скроллинга нажав на ctrl и движение колёсиком мыши. Также есть на экране кнопки слева и справа.

"перемещением мышки с удержанием левой кнопки" довольно сложно отлечить от других движений, чтобы позволить это определить за малый интервал времени и не затормозить дедектирование других действий.

Если после пары дней останется потребность в таком действие дай знать.
