### ISSUE TITLE
Мыльные шрифты в карточке фильма 

### ISSUE THREAD

**Issue by MihaxXx** [Mymem/site_ru#134]
Мыльные шрифты в карточке фильма в Chrome на OS X при отключенном в системе сглаживании и разрешении 1920*1080 
http://net2ftp.ru/node0/mikes22@yandex.ru/Screenshot_on_13,10_at_23-14-30.png

**Comment by shabanovd** [comment]
@MihaxXx на скрине этого уже не видно, какое железо?

**Comment by MihaxXx** [comment]
Железо
http://net2ftp.ru/node0/mikes22@yandex.ru/Image_on_14,10_at_10-51-42.png
http://net2ftp.ru/node0/mikes22@yandex.ru/Image_on_14,10_at_10-52-25.png
P.S.На Windows 10 Pro тоже самое http://net2ftp.ru/node0/mikes22@yandex.ru/Image_on_14,10_at_10-47-59.png

**Comment by shabanovd** [comment]
@MihaxXx сейчас размыливание есть? (нуно перегрузить страницу пару раз чтобы загрузился новая версия)

**Comment by MihaxXx** [comment]
@shabanovd На OS X проблемы больше нет, на винде позже гляну, но думаю там тоже решилось
Сейчас внимательно посмотрел - мылит ещё названия блоков: "ожидается релиз", "в кино" и т.д. (до сих пор есть проблема)

**Comment by shabanovd** [comment]
@MihaxXx ok, если заметишь где еще дай знать

**Comment by shabanovd** [comment]
fixed
