### ISSUE TITLE
После нажатия на персоны на первой странице переопределился символ. Перезапуск хрома не помог.

### ISSUE THREAD

**Issue by aldrd** [Mymem/site_ru#137]
<img width="160" alt="default" src="https://cloud.githubusercontent.com/assets/2474607/10484685/200d592c-728f-11e5-99f9-45dd902ab934.PNG">

**Comment by shabanovd** [comment]
предыдущий не у всех корректно отображался, пока заменил на этот. надо найди более подходящий

**Comment by aldrd** [comment]
лучше старый не у всех, чем этот у всех

**Comment by shabanovd** [comment]
скажем так, он не был у большинства

**Comment by gev** [comment]
а вот этот ▾ как на винде виден? (запушил)
