### ISSUE TITLE
Generation П не найти по поиску

### ISSUE THREAD

**Issue by aldrd** [Mymem/site_ru#144]
https://mymem.me/mneme/q/Generation

https://mymem.me/mneme/d/Xk7ofQBLQ9yvj8OMgh_a6Q

**Comment by shabanovd** [comment]
Поиск ограничен первыми 50 в выборке. Он не попал в эту выборку.

**Comment by aldrd** [comment]
Ограничение поиска можно использовать если есть сортировка по значимости

**Comment by shabanovd** [comment]
ее и нуно делать
