### ISSUE TITLE
Хотелось бы вернуть значки imdb и КП как было. Очень раздражает когда поиск все всремя в разном месте. Да и выглядит куце.

### ISSUE THREAD

**Issue by aldrd** [Mymem/site_ru#148]

**Comment by shabanovd** [comment]
там добаляется много других кнопок

**Comment by aldrd** [comment]
Это не оправдывает, ужасно, когда кнопки "прыгают"

**Comment by shabanovd** [comment]
с этим ничего не сделать, можно задерживать прорисоку пока не прийдет вся информация. но это будет черный экран на пару секунд

**Comment by aldrd** [comment]
Я не про анимацию, а про разнаые позиции в разных карточках

**Comment by shabanovd** [comment]
последовательность жестно определена, тебе просто не привычно

**Comment by shabanovd** [comment]
можно вики спустить вниз, тогда так сильно не будет прыгать

**Comment by aldrd** [comment]
если чего то нет, то все сдвигается. Результат "прыгет". Верни как было. Было хорошо.

**Comment by aldrd** [comment]
У всех важных фильмов все поля заполнены, поэтому место не освободить. Тогда не понятно зачем огород

**Comment by shabanovd** [comment]
потому что есть книги например, и у них другие ссылки. или там тоже держать IMDb и  KP?

**Comment by aldrd** [comment]
Зачем? Список должен быть индивидуален для каждого класса объектов.

**Comment by shabanovd** [comment]
нефакт, и это сложно в итоге
