### ISSUE TITLE
Фильм после релиза в iTunes (FullHD+Dolby 5.1) не перешёл из "чернового релиза" в просто "релиз"

### ISSUE THREAD

**Issue by MihaxXx** [Mymem/site_ru#150]
Я говорю про "Сюрприз" (De Surprise), возможно есть и другие
Скрин iTunes http://net2ftp.ru/node0/mikes22@yandex.ru/Screenshot_on_26,10_at_12-19-15.png

**Comment by shabanovd** [comment]
Админимы, которые следят за киоском не справляются. Придется автоматизировать этот процесс.

**Comment by MihaxXx** [comment]
@shabanovd В принципе могу предложить свою помощь, но мне кажется правильнее будет автоматизировать

**Comment by shabanovd** [comment]
@MihaxXx фильмами у нас занимаются 2 человека, Российским и Штатовским киосками. На подходе сериалы, если интерестно то можно будет их взять в администрирование.

Вообще редактировать можно все что кажется странным, могу расказать как.

**Comment by MihaxXx** [comment]
@shabanovd Если честно, сериалами в отличии от фильмов не интересуюсь
А отредактировать, найденную в процессе использования, ошибку это было бы хорошо, чтобы не создавать по каждому случаю issue,  расскажи.

**Comment by shabanovd** [comment]
@MihaxXx c "Сюрприз" разобрались, он не вышел еще в прокат. Начала проката 15.11.2015, сейчас он доступен для предзаказа только.

Долго думал убирать из "чернового" релиза или нет когда выходит "финальный". Пока решил оставлять. (эта штука очень специфична для России, так как выходы DVD накрылись тазиком)

Описание "как делать изменение" напишу на этой неделе. Могу быстро расказать если созвонимся скайпом (например), займет не более 5 минут.

**Comment by MihaxXx** [comment]
Как-то я это просмотрел, просто на торренте была пометка itunes и в самой

**Comment by MihaxXx** [comment]
@shabanovd Прокат - это аренда насколько я помню, а купить уже можно, разве нет? На торрентах, кстати, уже лежит версия из iTunes. 
Найди в скайпе mikes1945 
P.S. Даже не спрашивай почему такой логин XD

**Comment by shabanovd** [comment]
@MihaxXx с itunes пока путаница в том что они предоставлят два вида: покупка и прокат. Сам с этим путаюсь. Буду подправлять релиз с itunes по первой дате.

**Comment by shabanovd** [comment]
@MihaxXx вот ["как вносить изменения"](https://docs.google.com/document/d/1-QOvl2Nut55SP86fVQNhrfCrV2e57BiEurCjp3_i2gI/edit?usp=sharing)

**Comment by MihaxXx** [comment]
@shabanovd спасибо, а то руки до скайпа не дошли
