### ISSUE TITLE
Непонятно почему фильм в рекомендациях

### ISSUE THREAD

**Issue by aldrd** [Mymem/site_ru#159]
https://mymem.me/mneme/c/cinema/movies;v/forYou/2t0GS69RRAqP33GMJm0pGw;f/genres;d/xEVwzATKT8iL7RAZ5GO4hg

Никто из создателей не подчеркнут

**Comment by shabanovd** [comment]
Думаю из-за того, что сейчас список работ формируется по участию персоны без учета профессии участия.

**Comment by shabanovd** [comment]
fixed
