### ISSUE TITLE
тв-шоу показываются в каталоге фильмов

### ISSUE THREAD

**Issue by aldrd** [Mymem/site_ru#170]
Возможно не пересчитаны индексы

**Comment by shabanovd** [comment]
@aldrd скрин?

**Comment by aldrd** [comment]
https://mymem.me/mneme/c/cinema/movies;v/catalog/sts9joMeT-i7bMx2IfLz2g/fN5DIstdTZCKrAuvgsUwSw/all;f/NCmlcMuBTZ6f8P9R4zF5KA
![default](https://cloud.githubusercontent.com/assets/2474607/11559491/663e3c74-99ca-11e5-8909-55ad630db103.PNG)
https://mymem.me/cabinet/#0W7bWopcR6CQ7FhUa1exDw
