### ISSUE TITLE
Стоит сделать принудительное задане страны и языка через ссылку в адресной строке

### ISSUE THREAD

**Issue by aldrd** [Mymem/site_ru#172]
Такое задание надо использовать в рекламных ссылках, иначе велик шанс, что пользователи увидят английскую версию

**Comment by shabanovd** [comment]
а чем плох язык их браузера?

**Comment by aldrd** [comment]
Сейчас при незалогинегом заходе мне дается английский язык и США. Хотелось бы русский, язык броузера устраивает, но сейчас, похоже, не работает.
