### ISSUE TITLE
странный фильм без типа и оригинального названия. проставлен релиз, значит раньше фильм был впорядке

### ISSUE THREAD

**Issue by OksanaKovinskaia** [Mymem/site_ru#178]
https://mymem.me/cabinet/#2myLrAJTSxOyGPiV-P1clw

**Comment by OksanaKovinskaia** [comment]
https://mymem.me/cabinet/#mbOs-JhxS4GLFrzHg0JvLQ

**Comment by OksanaKovinskaia** [comment]
https://mymem.me/cabinet/#_KEahpYgRUS3ZrsnuRprqw

**Comment by OksanaKovinskaia** [comment]
https://mymem.me/cabinet/#J77T0s1uReqYdIxczK4Syg

**Comment by shabanovd** [comment]
@OksanaKovinskaia эти фильмы были удалены, сделай у себя reset.
