### ISSUE TITLE
есть фильмы "развалившиеся"

### ISSUE THREAD

**Issue by OksanaKovinskaia** [Mymem/site_ru#180]
https://mymem.me/cabinet/#D_eZS5d4S7exotaX862nNQ
https://mymem.me/cabinet/#kPnMC6T7Raa20t6jilu_Pg

**Comment by OksanaKovinskaia** [comment]
https://mymem.me/cabinet/#SWqYwBxEQpSbDtCW5SY3AQ

**Comment by shabanovd** [comment]
fixed
