### ISSUE TITLE
Сортировка по популярности барахлит

### ISSUE THREAD

**Issue by aldrd** [Mymem/site_ru#194]
https://mymem.me/mneme/c/cinema/movies;v/catalog/screenwriter/all/ndjSCLKHSC67ohyqXFPvFg;f/popularity  - Шерлок холмс Гая Ричи внизу списка

**Comment by aldrd** [comment]
https://mymem.me/mneme/c/cinema/movies;v/catalog/screenwriter/all/AQivfc44TsGgtsBcHRWdMw;f/popularity;d/Uin0ffShSJmLM6ePqPLyhw - Терминал идет последним

**Comment by shabanovd** [comment]
Терминал идет последним потому что мы не считаем голоса если сценаристов больше 3х, поэтому и второй Шерлок холмс Гая Ричи внизу.
