### ISSUE TITLE
При повторном пулреквесте не стоит писать, что он уже есть, а просто закрывать вкладку

### ISSUE THREAD

**Issue by aldrd** [Mymem/site_ru#20]

**Comment by shabanovd** [comment]
нельзя быть настолько ленивым, это информация ... кому-то она пригодится

**Comment by aldrd** [comment]
Придумай такие ситуации. Закрывать однозначно. Только путает.

**Comment by shabanovd** [comment]
что значит путает? не понятна информация или лень читать?

не показывается целый экран, и это нужно обосновать

**Comment by gev** [comment]
+1
