### ISSUE TITLE
Странности с режиссером

### ISSUE THREAD

**Issue by aldrd** [Mymem/site_ru#203]
https://mymem.me/mneme/p/iIye54QbR8C8K3ZytI1YXg;d/iIye54QbR8C8K3ZytI1YXg

Если нажать на его фильм https://mymem.me/cabinet/#BCvkzCDuTRiVfFJZNe_yeQ то будет другой режиссер

**Comment by shabanovd** [comment]
@aldrd сейчас нормально?

**Comment by shabanovd** [comment]
fixed
