### ISSUE TITLE
Для не вышедших фильмов

### ISSUE THREAD

**Issue by ghost** [Mymem/site_ru#206]
- Запретить ставить отметки "смотрел, хороший, пересмотреть" и прочие (оценки) для не вышедших в прокат фильмов
- Сделать в библиотеке место где будут ожидаемые не вышедшие фильмы

**Comment by shabanovd** [comment]
`Запретить ставить отметки "смотрел, хороший, пересмотреть" и прочие (оценки) для не вышедших в прокат фильмов` - согласен, нужно оставить только "хочу"

`Сделать в библиотеке место где будут ожидаемые не вышедшие фильмы` - это хотелки

**Comment by aldrd** [comment]
Не стоит запрещать. Есть очень много фильмов, которые появляются на торрентах задолго до выхода в кино.

**Comment by shabanovd** [comment]
@aldrd так мы этот факт как-то отмечаем или нет?

**Comment by aldrd** [comment]
Не всегда. Люди могут посмотреть фильм на английском задолго до выхода в российском прокате. Может появиться любительский перевод, мы это отслеживаем, но люди могут нас обогнать. Часто пираты выкладывают до премьеры, сейчас в штатах так утекло 30 фильмов. Есть предпремьерные показы для журналистов и блогеров.
Короче, не стоит ничего запрещать.
