### ISSUE TITLE
У Губенко этого фильма нет в актерских работах

### ISSUE THREAD

**Issue by aldrd** [Mymem/site_ru#207]
https://mymem.me/mneme/p/oZAp7tJPSMWCU5UvzQ1GYw;d/RYVDMC7QQ_eIyf5-QSyzqg

**Comment by shabanovd** [comment]
@aldrd у меня есть

**Comment by aldrd** [comment]
Если у фильма нет списка упорядоченных актеров, то неупорядоченные надо трактовать как "главные роли" и их надо показывать и в карточке фильма и в перечне работ персоны

**Comment by shabanovd** [comment]
@aldrd исправилось?
