### ISSUE TITLE
Проставил оценку "Один дома". Мне предложило умолчание "недавно", что неверно.

### ISSUE THREAD

**Issue by aldrd** [Mymem/site_ru#219]

**Comment by shabanovd** [comment]
@aldrd логика следующая: если за последний час небыло выставленно ни одной оценки, то считается что фильм был только что просмотрен. Если считать "недавно" только для последних двух лет, то промахнемся потому что не определим серию заполнения библиотеки. Текущий алгоритм хороший копромис.
