### ISSUE TITLE
Есть накладки по тексту

### ISSUE THREAD

**Issue by aldrd** [Mymem/site_ru#228]
https://mymem.me/mneme/c/cinema/movies;v/kiosk/0GMfSi1DTNGLpXlUkhmp8A;d/e8Q09zUCQJiVjtJGdmePrw

**Comment by shabanovd** [comment]
@aldrd не вижу

**Comment by aldrd** [comment]
Это хром

**Comment by aldrd** [comment]
![default](https://cloud.githubusercontent.com/assets/2474607/13728821/2d184b5a-e935-11e5-9aee-266f5a657380.PNG)

**Comment by shabanovd** [comment]
fixed
