### ISSUE TITLE
Стрелки вверх/вниз на клавиатуре приводят в движение все колонки сразу

### ISSUE THREAD

**Issue by aldrd** [Mymem/site_ru#242]

**Comment by shabanovd** [comment]
а что ты ожидал?

**Comment by aldrd** [comment]
Можно двигать тот столбец на котором стоит указатель мыши.

**Comment by shabanovd** [comment]
думаю что останется как есть, все варианты в итоге будут не коректы и самое правильно не поддерживать стрелки вверх-вниз.
