### ISSUE TITLE
В документальных фильмах в начале стоят обычные фильмы

### ISSUE THREAD

**Issue by aldrd** [Mymem/site_ru#248]

**Comment by aldrd** [comment]
https://mymem.me/mneme/c/cinema/docs;v/catalog/all;f/popularity

**Comment by shabanovd** [comment]
они отнесенны к "документальным" фильмам (смотри поле "это")

**Comment by aldrd** [comment]
Я их уже исправлял и у меня они стоят, как фильмы. Это к разговору о стрирании исправлений в локальном хранилище после их приемки.

**Comment by shabanovd** [comment]
тогда и называй проблему правильно -)

**Comment by shabanovd** [comment]
у меня тогда вопрос, почему после того как ты внес изменения они опять стали "документальными" фильмами?
