### ISSUE TITLE
Summer Love странно ищет

### ISSUE THREAD

**Issue by OksanaKovinskaia** [Mymem/site_ru#255]
https://mymem.me/cabinet#FbjnABTHSu20jwR2jlbu_Q этот фильм не ищется по названию с сайта, но ищется через админку.

**Comment by OksanaKovinskaia** [comment]
https://mymem.me/cabinet#ZnpdQvSfSGeTPSNfxDsTIQ  , http://www.imdb.com/title/tt3620846/  не ищет по названию и imdb

**Comment by shabanovd** [comment]
https://mymem.me/cabinet#ZnpdQvSfSGeTPSNfxDsTIQ имеет другую ссылку imdb http://www.imdb.com/title/tt4796560/
