### ISSUE TITLE
Ошибка при входе через FB

### ISSUE THREAD

**Issue by antmusin** [Mymem/site_ru#302]
Не могу войти в свой профиль через facebook. Выдает ошибку. Скрин ошибки приложил.
![image](https://user-images.githubusercontent.com/61546080/75443988-97233700-5973-11ea-81a3-ba9b75f17b69.png)

**Comment by shabanovd** [comment]
скорей всего проблема в использовании http протокола, что будет если зайти на сайт по https://mymem.me ?

**Comment by shabanovd** [comment]
Можно ссылку по которой на сайт?

**Comment by antmusin** [comment]
Все в порядке. Действительно, заходил через незащищенный протокол
