### ISSUE TITLE
В моих хотелках первым стоит фильм 1982 года, затем 2014, далее 2015 

### ISSUE THREAD

**Issue by aldrd** [Mymem/site_ru#54]

**Comment by aldrd** [comment]
![default](https://cloud.githubusercontent.com/assets/2474607/8609088/09d2eb62-26aa-11e5-86f3-d16881662076.png)

**Comment by aldrd** [comment]
![default](https://cloud.githubusercontent.com/assets/2474607/8609095/24393c18-26aa-11e5-9090-84f65165f0d9.PNG)

**Comment by shabanovd** [comment]
это уже должно быть исправлено

**Comment by aldrd** [comment]
пока остается

**Comment by shabanovd** [comment]
исправлено?
