### ISSUE TITLE
У меня в хотелках нет Мира Юрского периода и Терминатора, хотя они помечены

### ISSUE THREAD

**Issue by aldrd** [Mymem/site_ru#56]

**Comment by shabanovd** [comment]
был баг, который уже пофикшен. Нужно пройтись и подправить данные в персональных хранилищах.

**Comment by aldrd** [comment]
Попробовал удалить из хотелок и добавить снова. Появились.

**Comment by shabanovd** [comment]
помогло? нужно просто еще раз нажать, если хочешь руками исправит.
