### ISSUE TITLE
Сортировка глючит. Большой куш стоит последним.

### ISSUE THREAD

**Issue by aldrd** [Mymem/site_ru#85]
https://mymem.me/#c/cinema/movies;v/catalog/poSMIZNsTVyhHweKgQ02IQ/AAAAAAAAB9AAAAAAAAAH2Q/mlHLO0cORdK-rIdOsC2ucQ;f/NCmlcMuBTZ6f8P9R4zF5KA

**Comment by shabanovd** [comment]
Все правильно, для этого актера количество голосов в этом фильме ноль
