### ISSUE TITLE
В списке работ фильмы должны сортироваться по году, а не по выходу в прокат.

### ISSUE THREAD

**Issue by aldrd** [Mymem/site_ru#94]
https://mymem.me/cabinet/#qQxqgj4lThCsFI434zK4ig - год 1980, прокат Россия 1993

**Comment by shabanovd** [comment]
и да, и нет ... при сортировки по году, внутри года нужно сортировать по дате примьеры. Это особенно кретично для текщего года.

**Comment by aldrd** [comment]
Ошибиться внутри года меньшее из зол, можно этим пренибречь. Сортировка по премьере слишком часто дает бред для России. Стоит сортировать по годам, а внутри лет по премьерам.

**Comment by shabanovd** [comment]
про то и разговор, что там есть баг

**Comment by shabanovd** [comment]
fixed
